# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7737b16d174ca96cf944326868eb9a2984a66d5bf6c2ca180154e3a16c4ddc7ac4ad0f67cabbeec7dff8ba815a5c938a102260cfb3edbbc3e60d7171f7dd7b64

test:
  secret_key_base: eeb03d3120ca253eb13c43325f57a57f2c37387cd20a0ef4651beb7074c8d954462d0a80cdda104d30584d118d8b83f4d97b7580b6870ff6180105ccddd990bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
